// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHTPk8uTDQ9Y7GerkSfcSPMcqEJWPmWCA',
    appId: '1:1036930558286:web:b308908091c3e4684f161f',
    messagingSenderId: '1036930558286',
    projectId: 'e-learning-app-8497a',
    authDomain: 'e-learning-app-8497a.firebaseapp.com',
    storageBucket: 'e-learning-app-8497a.appspot.com',
    measurementId: 'G-Z1HZ2KXTTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOb1fDMdePUe1o9496yrjg7d1eQUzFgwQ',
    appId: '1:1036930558286:android:c6112513f519e47e4f161f',
    messagingSenderId: '1036930558286',
    projectId: 'e-learning-app-8497a',
    storageBucket: 'e-learning-app-8497a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6X5yP0IH9W9FIKxZNP9fGuyDRq4-gSQ',
    appId: '1:1036930558286:ios:fdb9ed577c8c9f8d4f161f',
    messagingSenderId: '1036930558286',
    projectId: 'e-learning-app-8497a',
    storageBucket: 'e-learning-app-8497a.appspot.com',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO6X5yP0IH9W9FIKxZNP9fGuyDRq4-gSQ',
    appId: '1:1036930558286:ios:fdb9ed577c8c9f8d4f161f',
    messagingSenderId: '1036930558286',
    projectId: 'e-learning-app-8497a',
    storageBucket: 'e-learning-app-8497a.appspot.com',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHTPk8uTDQ9Y7GerkSfcSPMcqEJWPmWCA',
    appId: '1:1036930558286:web:3b20aae82330bcbf4f161f',
    messagingSenderId: '1036930558286',
    projectId: 'e-learning-app-8497a',
    authDomain: 'e-learning-app-8497a.firebaseapp.com',
    storageBucket: 'e-learning-app-8497a.appspot.com',
    measurementId: 'G-DBVKBXSW1S',
  );
}
